////////////////////////////////////////////////////////////
//
// ! Generated by make-ast.py.
// ! Changes to this file will be lost during regeneration.
//
////////////////////////////////////////////////////////////


#nullable disable

namespace CsLox;

public abstract class Expression { }

public class Binary : Expression
{
    public Expression left;
    public LoxToken op;
    public Expression right;
}

public class Grouping : Expression
{
    public Expression expr;
}

public class Literal : Expression
{
    public object val;
}

public class Unary : Expression
{
    public LoxToken op;
    public Expression expr;
}

